### ISSUE TITLE
@Mention works only at end of msg

### ISSUE THREAD

**Issue by the-itz** [arminfro/participator#3]
We have to define the behaviour if the user presses @ in the middle of a message. Currently we just add the string to the end of the message. 
My proposal would be that it works also in the middle of the text (currently no idea how to do this :-) )

**Comment by arminfro** [comment]
True, what would be a good behavior for this situation?! Normally, we use @ only to type e-mail addresses. 

So I guess the following makes sense:
(1) If the previous character is a letter, we should prevent the trigger for At-Mention.
(2) If the previous character is a space, we should just trigger At-Mention.
(3) If the previous character is not a letter and not a space, we should trigger At-Mention and insert a space before.

How to: Test for (1) with `isLetter` (function is already defined), `else if` test for (2), `else` (3)

**Comment by the-itz** [comment]
solved with last commit. Pls verify
