### ISSUE TITLE
Single new line characters in `ChatInputForm` doesn't seem to work

### ISSUE THREAD

**Issue by arminfro** [arminfro/participator#5]
This is a markdown specification. A single new line doesn't output a new line.

Solution is to add one `\` or two spaces at the end of the line, see [SO answer](https://stackoverflow.com/a/26626346). Then markdown outputs a line break.

I'm not sure about the best solution, let's just try to replace `\n` with just `\`, if there is only one `\n`. 
Maybe you have a better idea!? :wink: 

Edit: Maybe `breaks` option is better suited, see [here](https://marked.js.org/using_advanced)

**Comment by the-itz** [comment]
@arminfro please try again, I think the last commit should solve this.
I've added the breaks option in marked.
