### ISSUE TITLE
Deleting a message with children, also deletes the children

### ISSUE THREAD

**Issue by the-itz** [arminfro/participator#8]
My proposed behaviour would be to change the orginal message into something like: "Message was deleted / Nachricht wurde gelöscht" and keep the children.

**Comment by arminfro** [comment]
I thought so too, I'll do that on the server side.

**Comment by arminfro** [comment]
[Fixed in 346f5e2](https://github.com/arminfro/participator/commit/346f5e23d35b35cbb963cb693d6def9fd041b320)
